Cleanup EFA-Configure & fixed ipchange

diff --git a/build/EFA/EFA-Configure b/build/EFA/EFA-Configure
--- a/build/EFA/EFA-Configure
+++ b/build/EFA/EFA-Configure
@@ -24,28 +24,28 @@ debug="1"
 # +---------------------------------------------------+
 show_menu() {
     menu=1
-	while [ $menu == "1" ]
-		do
-			func_echo-header 
-			echo -e "Please select the item you want to modify"
-			echo -e " "
-			echo -e "0)  Logout                              4)  IP Settings"
-			echo -e "1)  Shell                                                    "
-			echo -e "2)  Reboot system                                       "
-			echo -e "3)  Halt system                                           "
-			echo -e ""
-			echo -e -n "$green[EFA]$clean : "
-			local choice
-			read choice
-			case $choice in
-					0) exit && exit  && logout ;;
-					1) exit 0 ;;
-					2) func_reboot ;;
-					3) func_halt ;;
-					4) func_ip-settings ;;
-					*) echo -e "Error \"$choice\" is not an option..." && sleep 2
-			esac
-		done
+    while [ $menu == "1" ]
+        do
+            func_echo-header 
+            echo -e "Please select the item you want to modify"
+            echo -e " "
+            echo -e "0)  Logout                              4)  IP Settings"
+            echo -e "1)  Shell                                              "
+            echo -e "2)  Reboot system                                      "
+            echo -e "3)  Halt system                                       	"
+            echo -e ""
+            echo -e -n "$green[EFA]$clean : "
+            local choice
+            read choice
+            case $choice in
+                    0) exit && exit  && logout ;;
+                    1) exit 0 ;;
+                    2) func_reboot ;;
+                    3) func_halt ;;
+                    4) func_ip-settings ;;
+                    *) echo -e "Error \"$choice\" is not an option..." && sleep 2
+            esac
+        done
 }
 # +---------------------------------------------------+
 
@@ -53,62 +53,62 @@ show_menu() {
 # Option IP_SETTINGS
 # +---------------------------------------------------+
 func_ip-settings(){
-	menu=0
-	ipmenu=1
-	while [ $ipmenu == "1" ]
-		do
-			func_getipsettings
-			func_echo-header
-			echo -e "Current IP settings for $INTERFACE are:"
-			echo -e "1) IP					:  $IP"
-			echo -e "2) Netmask				:  $NM"
-			echo -e "3) Gateway				:  $GW"
-			echo -e "4) Primary DNS			:  $DNS1"
-			echo -e "5) Secondary DNS		:  $DNS2"
-			echo -e ""
-			echo -e "e) Return to main menu"
-			echo -e ""
-			echo -e "Note: Network will reset when changing values."
-			echo -e ""
-			echo -e "Enter setting you want to change"
-			echo -e -n "$green[EFA]$clean : "
-			local choice
-			read choice
-			case $choice in
-				1) 	ipmenu=0
-					echo ""
-					read -p "Enter your new IP: " IP
-					func_setipsettings
-					menu=1
-					;;
-				2)  ipmenu=0
-					echo ""
-					read -p "Enter your new netmask: " NM
-					func_setipsettings
-					menu=1
-					;;
-				3)  ipmenu=0
-					echo ""
-					read -p "Enter your new gateway: " GW
-					func_setipsettings
-					menu=1
-					;;
-				4) 	ipmenu=0
-					echo ""
-					read -p "Enter your new primary DNS: " DNS1
-					func_setipsettings
-					menu=1
-					;;
-				5) 	ipmenu=0
-					echo ""
-					read -p "Enter your new secondary DNS: " DNS2
-					func_setipsettings
-					menu=1
-					;;
-				e) menu=1 && return ;;
-				*) echo -e "Error \"$choice\" is not an option..." && sleep 2
-			esac
-		done
+    menu=0
+    ipmenu=1
+    while [ $ipmenu == "1" ]
+        do
+            func_getipsettings
+            func_echo-header
+            echo -e "Current IP settings for $INTERFACE are:"
+            echo -e "1) IP			:  $IP"
+            echo -e "2) Netmask		:  $NM"
+            echo -e "3) Gateway		:  $GW"
+            echo -e "4) Primary DNS		:  $DNS1"
+            echo -e "5) Secondary DNS	:  $DNS2"
+            echo -e ""
+            echo -e "e) Return to main menu"
+            echo -e ""
+            echo -e "Note: Network will reset when changing values."
+            echo -e ""
+            echo -e "Enter setting you want to change"
+            echo -e -n "$green[EFA]$clean : "
+            local choice
+            read choice
+            case $choice in
+                1) 	ipmenu=0
+                    echo ""
+                    read -p "Enter your new IP: " IP
+                    func_setipsettings
+                    menu=1
+                    ;;
+                2)  ipmenu=0
+                    echo ""
+                    read -p "Enter your new netmask: " NM
+                    func_setipsettings
+                    menu=1
+                    ;;
+                3)  ipmenu=0
+                    echo ""
+                    read -p "Enter your new gateway: " GW
+                    func_setipsettings
+                    menu=1
+                    ;;
+                4) 	ipmenu=0
+                    echo ""
+                    read -p "Enter your new primary DNS: " DNS1
+                    func_setipsettings
+                    menu=1
+                    ;;
+                5) 	ipmenu=0
+                    echo ""
+                    read -p "Enter your new secondary DNS: " DNS2
+                    func_setipsettings
+                    menu=1
+                    ;;
+                e) menu=1 && return ;;
+                *) echo -e "Error \"$choice\" is not an option..." && sleep 2
+            esac
+        done
 }
 # +---------------------------------------------------+
 
@@ -116,30 +116,25 @@ func_ip-settings(){
 # Function to grab the current IP settings.
 # +---------------------------------------------------+
 function func_getipsettings(){
-	nrintf=`cat /proc/net/dev | grep eth | awk {' print $1 '} | sed 's/://g' | wc -l`
-	interf=`cat /proc/net/dev | grep eth | awk {' print $1 '} | sed 's/://g'`
-	IP="`cat /etc/network/interfaces.d/$INTERFACE | grep address | awk {' print $2 '}`"
-	NM="`cat /etc/network/interfaces.d/$INTERFACE | grep netmask | awk {' print $2 '}`"
-	GW="`cat /etc/network/interfaces.d/$INTERFACE | grep gateway | awk {' print $2 '}`"
-	DNS1="`cat /etc/resolv.conf  | grep -v '#' | grep -v 127.0.0.1 | grep nameserver | awk 'NR==1 {print $2}'`"
-	DNS2="`cat /etc/resolv.conf  | grep -v '#' | grep -v 127.0.0.1 | grep nameserver | awk 'NR==2 {print $2}'`"
-	if [ $nrintf -gt 1 ]
-	 then
-		func_echo-header
-		echo -e "You seem to have multiple network interfaces"
-		echo -e "Please select the interface you want to configure"
-		echo -e "The interface names on your machine are:"
-		for int in $interf
-			do
-				echo " - $int"
-			done
+    nrintf=`cat /proc/net/dev | grep eth | awk {' print $1 '} | sed 's/://g' | wc -l`
+    interf=`cat /proc/net/dev | grep eth | awk {' print $1 '} | sed 's/://g'`
+    if [ $nrintf -gt 1 ]
+     then
+        func_echo-header
+        echo -e "You seem to have multiple network interfaces"
+        echo -e "Please select the interface you want to configure"
+        echo -e "The interface names on your machine are:"
+        for int in $interf
+            do
+                echo " - $int"
+            done
 
-		echo -e ""
-		echo -e "Enter the primary interface name:"
-		echo -e ""
-		echo -e -n "$green[EFA]$clean : "
-		local choice
-		read choice
+        echo -e ""
+        echo -e "Enter the primary interface name:"
+        echo -e ""
+        echo -e -n "$green[EFA]$clean : "
+        local choice
+        read choice
         choice_check=0
         for int in $interf
          do
@@ -148,7 +143,7 @@ function func_getipsettings(){
             choice_check=1
            fi
          done
-		 
+         
          # Check if the user typed a interface that exists.
          if [ $choice_check -eq 0 ]
           then
@@ -163,9 +158,14 @@ function func_getipsettings(){
           INTERFACE=$choice
         fi
 
-  else
+     else
         INTERFACE=$interf
-fi
+    fi
+    IP="`cat /etc/network/interfaces.d/$INTERFACE | grep address | awk {' print $2 '}`"
+    NM="`cat /etc/network/interfaces.d/$INTERFACE | grep netmask | awk {' print $2 '}`"
+    GW="`cat /etc/network/interfaces.d/$INTERFACE | grep gateway | awk {' print $2 '}`"
+    DNS1="`cat /etc/resolv.conf  | grep -v '#' | grep -v 127.0.0.1 | grep nameserver | awk 'NR==1 {print $2}'`"
+    DNS2="`cat /etc/resolv.conf  | grep -v '#' | grep -v 127.0.0.1 | grep nameserver | awk 'NR==2 {print $2}'`"
 }
 # +---------------------------------------------------+
 
@@ -173,63 +173,63 @@ fi
 # Function to set the new IP settings
 # +---------------------------------------------------+
 func_setipsettings(){
-	for ip in $IP $NM $GW $DNS1 $DNS2
-		do
-			validcheck=1
-			while [ $validcheck != 0 ]
-				do
-					if checkip $ip
-						then
-							validcheck=0
-						else
-							echo "ERROR: The value $ip seems to be invalid"
-							pause
-							return
-					fi
-				done
-		done
-	# Grab current FQDN
-	HOSTNAME="`cat /etc/mailname | sed  's/\..*//'`"
-	DOMAINNAME="`cat /etc/mailname | sed -n 's/[^.]*\.//p'`"
+    for ip in $IP $NM $GW $DNS1 $DNS2
+        do
+            validcheck=1
+            while [ $validcheck != 0 ]
+                do
+                    if checkip $ip
+                        then
+                            validcheck=0
+                        else
+                            echo "ERROR: The value $ip seems to be invalid"
+                            pause
+                            return
+                    fi
+                done
+        done
+    # Grab current FQDN
+    HOSTNAME="`cat /etc/mailname | sed  's/\..*//'`"
+    DOMAINNAME="`cat /etc/mailname | sed -n 's/[^.]*\.//p'`"
 
-	# Stopping services
-	/etc/init.d/rabbitmq-server	stop >> /dev/null
+    # Stopping services
+    /etc/init.d/rabbitmq-server	stop >> /dev/null
 
-	# Edit hosts file
-	echo "127.0.0.1		localhost  localhost.localdomain" > /etc/hosts
-	echo "$IP	$HOSTNAME.$DOMAINNAME	$HOSTNAME" >> /etc/hosts
-	echo "" >> /etc/hosts
-	echo "# The following lines are desirable for IPv6 capable hosts" >> /etc/hosts
-	echo "::1     ip6-localhost ip6-loopback" >> /etc/hosts
-	echo "fe00::0 ip6-localnet" >> /etc/hosts
-	echo "ff00::0 ip6-mcastprefix" >> /etc/hosts
-	echo "ff02::1 ip6-allnodes" >> /etc/hosts
-	echo "ff02::2 ip6-allrouters" >> /etc/hosts
+    # Edit hosts file
+    echo "127.0.0.1		localhost  localhost.localdomain" > /etc/hosts
+    echo "$IP	$HOSTNAME.$DOMAINNAME	$HOSTNAME" >> /etc/hosts
+    echo "" >> /etc/hosts
+    echo "# The following lines are desirable for IPv6 capable hosts" >> /etc/hosts
+    echo "::1     ip6-localhost ip6-loopback" >> /etc/hosts
+    echo "fe00::0 ip6-localnet" >> /etc/hosts
+    echo "ff00::0 ip6-mcastprefix" >> /etc/hosts
+    echo "ff02::1 ip6-allnodes" >> /etc/hosts
+    echo "ff02::2 ip6-allrouters" >> /etc/hosts
 
-	# Edit resolv.conf
-	echo "nameserver 127.0.0.1" > /etc/resolv.conf
-	echo "nameserver $DNS1" >> /etc/resolv.conf
-	echo "nameserver $DNS2" >> /etc/resolv.conf
-	
-	/etc/init.d/networking stop >> /dev/null
-	# Edit interfaces
-	echo "auto $INTERFACE" > /etc/network/interfaces.d/$INTERFACE
-	echo "iface $INTERFACE inet static" >> /etc/network/interfaces.d/$INTERFACE
-	if [ -n "$IP" ]; then
-		echo "        address $IP" >> /etc/network/interfaces.d/$INTERFACE
-	fi
-	if [ -n "$NM" ]; then
-		echo "        netmask $NM" >> /etc/network/interfaces.d/$INTERFACE
-	fi
-	if [ -n "$GW" ]; then
-		echo "        gateway $GW" >> /etc/network/interfaces.d/$INTERFACE
-	fi
-	
-	echo ""
-	/etc/init.d/networking start
-	/etc/init.d/rabbitmq-server	start >> /dev/null
-	echo ""
-	pause
+    # Edit resolv.conf
+    echo "nameserver 127.0.0.1" > /etc/resolv.conf
+    echo "nameserver $DNS1" >> /etc/resolv.conf
+    echo "nameserver $DNS2" >> /etc/resolv.conf
+    
+    /etc/init.d/networking stop >> /dev/null 2>&1
+    # Edit interfaces
+    echo "auto $INTERFACE" > /etc/network/interfaces.d/$INTERFACE
+    echo "iface $INTERFACE inet static" >> /etc/network/interfaces.d/$INTERFACE
+    if [ -n "$IP" ]; then
+        echo "        address $IP" >> /etc/network/interfaces.d/$INTERFACE
+    fi
+    if [ -n "$NM" ]; then
+        echo "        netmask $NM" >> /etc/network/interfaces.d/$INTERFACE
+    fi
+    if [ -n "$GW" ]; then
+        echo "        gateway $GW" >> /etc/network/interfaces.d/$INTERFACE
+    fi
+
+    /etc/init.d/networking start >> /dev/null 2>&1
+    /etc/init.d/rabbitmq-server	start >> /dev/null 2>&1
+    echo ""
+    echo -e "All done"
+    pause
 }
 # +---------------------------------------------------+
 
@@ -245,7 +245,7 @@ fi
 # Pause
 # +---------------------------------------------------+
 pause(){
-	read -p "Press [Enter] key to continue..." fackEnterKey
+    read -p "Press [Enter] key to continue..." fackEnterKey
 }
 # +---------------------------------------------------+
 
@@ -253,18 +253,18 @@ pause(){
 # Function to test IP addresses
 # +---------------------------------------------------+
 function checkip(){
-	local ip=$1
-	local stat=1
+    local ip=$1
+    local stat=1
 
-	if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
-		OIFS=$IFS
-		IFS='.'
-		ip=($ip)
-		IFS=$OIFS
-		[[ ${ip[0]} -le 255 && ${ip[1]} -le 255 && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
-		stat=$?
-	fi
-	return $stat
+    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+        OIFS=$IFS
+        IFS='.'
+        ip=($ip)
+        IFS=$OIFS
+        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
+        stat=$?
+    fi
+    return $stat
 }
 # +---------------------------------------------------+
 
@@ -273,25 +273,25 @@ function checkip(){
 # +---------------------------------------------------+
 func_reboot() {
     menu=0
-	rebootmenu=1
-	while [ $rebootmenu == "1" ]
-		do
-			func_echo-header 
-			echo -e "Are you sure you want to reboot this host?"
-			echo -e ""
-			echo -e "Y)  Yes I am sure"
-			echo -e "N)  No no no take me back!"
-			echo -e ""
-			echo -e -n "$green[EFA]$clean : "
-			local choice
-			read choice
-			case $choice in
-					Y) reboot && exit 0 ;;
-					N) menu=1 && return  ;;
-					n) menu=1 && return  ;;
-					*) echo -e "Error \"$choice\" is not an option..." && sleep 2
-			esac
-		done
+    rebootmenu=1
+    while [ $rebootmenu == "1" ]
+        do
+            func_echo-header 
+            echo -e "Are you sure you want to reboot this host?"
+            echo -e ""
+            echo -e "Y)  Yes I am sure"
+            echo -e "N)  No no no take me back!"
+            echo -e ""
+            echo -e -n "$green[EFA]$clean : "
+            local choice
+            read choice
+            case $choice in
+                    Y) reboot && exit 0 ;;
+                    N) menu=1 && return  ;;
+                    n) menu=1 && return  ;;
+                    *) echo -e "Error \"$choice\" is not an option..." && sleep 2
+            esac
+        done
 }
 # +---------------------------------------------------+
 
@@ -300,25 +300,25 @@ func_reboot() {
 # +---------------------------------------------------+
 func_halt() {
     menu=0
-	haltmenu=1
-	while [ $haltmenu == "1" ]
-		do
-			func_echo-header 
-			echo -e "Are you sure you want to halt this host?"
-			echo -e ""
-			echo -e "Y)  Yes I am sure"
-			echo -e "N)  No no no take me back!"
-			echo -e ""
-			echo -e -n "$green[EFA]$clean : "
-			local choice
-			read choice
-			case $choice in
-					Y) shutdown -h now && exit 0 ;;
-					N) menu=1 && return  ;;
-					n) menu=1 && return  ;;
-					*) echo -e "Error \"$choice\" is not an option..." && sleep 2
-			esac
-		done
+    haltmenu=1
+    while [ $haltmenu == "1" ]
+        do
+            func_echo-header 
+            echo -e "Are you sure you want to halt this host?"
+            echo -e ""
+            echo -e "Y)  Yes I am sure"
+            echo -e "N)  No no no take me back!"
+            echo -e ""
+            echo -e -n "$green[EFA]$clean : "
+            local choice
+            read choice
+            case $choice in
+                    Y) shutdown -h now && exit 0 ;;
+                    N) menu=1 && return  ;;
+                    n) menu=1 && return  ;;
+                    *) echo -e "Error \"$choice\" is not an option..." && sleep 2
+            esac
+        done
 }
 # +---------------------------------------------------+
 
@@ -351,14 +351,14 @@ cyan='\E[00;36m'
 clean='\e[00m'
 
 if [ `whoami` == root ]
-	then
-		menu="1"
-		while [ $menu == "1" ]
-		do
-			show_menu
-		done
-	else
-		echo -e "$red [EFA] ERROR: Please become root.$clean"
-		exit 0
-	fi
+    then
+        menu="1"
+        while [ $menu == "1" ]
+        do
+            show_menu
+        done
+    else
+        echo -e "$red [EFA] ERROR: Please become root.$clean"
+        exit 0
+    fi
 # +---------------------------------------------------+
